### ISSUE TITLE
Error: cant import views & processing

### ISSUE THREAD

**Issue by busiing** [oemof/marketlib#4]
Traceback (most recent call last):
  File "C:/Users/swehkamp/Documents/GitHub/FlexValue/09_Sammelpaper 2/EnergyMarketsSimulation/main.py", line 19, in <module>
    from src.district_model_4_markets import main as district_model
  File "C:\Users\swehkamp\Documents\GitHub\FlexValue\09_Sammelpaper 2\EnergyMarketsSimulation\src\district_model_4_markets.py", line 20, in <module>
    from oemof.solph import views, processing
ImportError: cannot import name 'views' from 'oemof.solph' (C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oemof\solph\__init__.py)

**Comment by busiing** [comment]
In 0.3.2 GenericStorage isnt part of solphs init.

**Comment by busiing** [comment]
It has to be imported from outputlib.

**Comment by Fernando3161** [comment]
Need to update the requirements.txt file with a current oemof version
