### ISSUE TITLE
Error: market_data.csv wont be created by initial use

### ISSUE THREAD

**Issue by busiing** [oemof/marketlib#7]
```
WARNING:root:No district data found for year 2020. Using year 2017
Traceback (most recent call last):
  File "C:/Users/swehkamp/Documents/GitHub/FlexValue/09_Sammelpaper 2/EnergyMarketsSimulation/main.py", line 25, in <module>
    district_model(year=2020, days = 365)
  File "C:\Users\swehkamp\Documents\GitHub\FlexValue\09_Sammelpaper 2\EnergyMarketsSimulation\src\district_model_4_markets.py", line 515, in main
    create_and_solve_scenario(days=days, year=year, scenario=scenario)
  File "C:\Users\swehkamp\Documents\GitHub\FlexValue\09_Sammelpaper 2\EnergyMarketsSimulation\src\district_model_4_markets.py", line 505, in create_and_solve_scenario
    market_data = get_market_dataframe(days=days, year=year, scenario=scenario)
  File "C:\Users\swehkamp\Documents\GitHub\FlexValue\09_Sammelpaper 2\EnergyMarketsSimulation\src\district_model_4_markets.py", line 132, in get_market_dataframe
    market_data = get_market_data(year=year).head(days * 24 * 4)
  File "C:\Users\swehkamp\Documents\GitHub\FlexValue\09_Sammelpaper 2\EnergyMarketsSimulation\src\process_market_data.py", line 148, in get_market_data
    df = read_market_data(start, periods, freq)
  File "C:\Users\swehkamp\Documents\GitHub\FlexValue\09_Sammelpaper 2\EnergyMarketsSimulation\src\process_market_data.py", line 93, in read_market_data
    df=pd.read_csv(market_filename)
  File "C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\swehkamp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\swehkamp\\Documents\\GitHub\\FlexValue\\09_Sammelpaper 2\\EnergyMarketsSimulation\\data\\processed\\market_data.csv'

Process finished with exit code 1
```

It is necessary to run process_market_data.py first.

**Comment by Fernando3161** [comment]
Yes. I see that now. I should there include a condition to create the data if it does not exists.

I will fix it.

**Comment by Fernando3161** [comment]
Fixed in yesterdays commit
